### ISSUE TITLE
[Feature] Adding a Favicon 

### ISSUE THREAD

**Issue by kumarankit999** [cncf/landscape2#190]
There isn't any favicon currently for landscape2. So, We can add a new favicon for landscape2, which will be of

![image](https://github.com/cncf/landscape2/assets/111564362/b53dfb9e-acd7-4399-bcef-362d4bb3d580)

**Comment by tegioz** [comment]
Thanks @kumarankit999. We are making [this configurable](https://github.com/cncf/landscape2-sites/blob/68197167d313edce23cdda9269a9ac8b1e0142d0/cncf/settings.yml#L25) from the settings file instead of adding a single icon, @cynthia-sg is already working on this.

The reason is that the tool must be able to generate multiple landscapes, and each one may use a different icon (in the same way they use a different logo or colors). You can see some of them in the [landscape2-sites repo](https://github.com/cncf/landscape2-sites#landscape2-sites) 🙂

**Comment by kumarankit999** [comment]
OK I see
