### ISSUE TITLE
New cookie for landscape

### ISSUE THREAD

**Issue by caniszczyk** [cncf/landscape2#463]
<script type="text/javascript" id="hs-script-loader" async defer src="//[js.hs-scripts.com/8112310.js?businessUnitId=983905](http://js.hs-scripts.com/8112310.js?businessUnitId=983905)"></script>

We need this for our CRM :)

**Comment by tegioz** [comment]
I guess this is something CNCF specific.

BTW yesterday we added support for loading Google Tag Manager containers on the new landscape. Using them, @cjyabraham is now loading some tags on the CNCF landscape, like GA and HubSpot. Is this somehow related and maybe already covered, or is this a different HubSpot tag? If it's a different tag, it'd be great if it could be loaded by using the GTM container we have in the CNCF landscape.

Otherwise we need to think about a way to make this configurable per landscape 🤔

**Comment by cjyabraham** [comment]
This tag is already being provided by the GTM running on landscape so we're good here.
