### ISSUE TITLE
Make CNCF landscape footer more aligned with other CNCF subsite footers

### ISSUE THREAD

**Issue by cjyabraham** [cncf/landscape2#469]
All CNCF subsites have a similar [footer](https://glossary.cncf.io/):

![Screenshot 2024-01-24 at 10 23 44 AM](https://github.com/cncf/landscape2/assets/463160/0683c22e-ee25-43c2-a049-0ea9f9caef74)

Is it possible to bring the landscape footer more in line with this design. Also see that all these footers have a "All CNCF Sites" button that links to [this page](https://www.cncf.io/all-cncf/). Could this be added to the landscape footer?

**Comment by tegioz** [comment]
Hi Chris

They already look quite similar! 😅

![landscape-footer](https://github.com/cncf/landscape2/assets/1213902/ca606c43-aced-4823-b44f-985a0908e360)

We could do some minor tweaks like moving the icons to the right side, removing the QR code and moving the project/community/about sections to the top, but it looks like something minimal.

It's important to keep in mind that we have [more landscapes generated with this tool than the CNCF's](https://github.com/cncf/landscape2-sites#landscape2-sites) (and that it will be probably used beyond LF foundations soon). At some point the footer used across the CNCF subsites may change, and maybe at that point it wouldn't be nice to change all the existing landscapes footers just to match CNCF's. We've tried to make them look similar as of today, but IMHO it's ok if they are not identical and evolve differently over time, so that the landscape can maintain its own identity. The previous landscape, for example, didn't even have that footer IIRC.

Regarding the `All CNCF Sites` button: every time we do something CNCF specific, we need to make it configurable as we cannot apply it to all existing landscapes. This will increase the complexity of the settings file and the landscape generation tool, and over time this will add up. It's possible to do this every time it's really needed, but I think we should be mindful about this and only introduce this additional complexity when the value added is worth it 🙂

**Comment by tegioz** [comment]
We've made some adjustments to the footer in #474. It looks more similar to the other CNCF sites now (although not identical).

Will close this issue for now, please feel free to reopen if needed 🙂

**Comment by cjyabraham** [comment]
Ok, cool. Looks more closely aligned now. Is it possible to link the CNCF logo to the CNCF site? It seems that having the footer logo link out to a particular url might be a common request and not unique to CNCF?

**Comment by tegioz** [comment]
Done!
