### ISSUE TITLE
Add link for docs

### ISSUE THREAD

**Issue by jmertic** [cncf/landscape2#629]
We have many projects that leverage ReadTheDocs for documentation; it would be awesome if we could at least have a link to the docs in the project card, but if it could be auto-discovered, that would be awesome! LMK if you have any questions - thanks in advance!

**Comment by tegioz** [comment]
Hi @jmertic 👋 

This one may be already solved, please see: https://github.com/cncf/landscape2/issues/618#issuecomment-2104097185 🙂

**Comment by jmertic** [comment]
Hey - so yes and no. You are right; you could do it this way. But I view docs as at the level of the icons listed in the top right corner of the card; it's a critical thing we want to drive projects to have and something users will look for.

LMK if this makes sense - like I said what you suggested would work, but an icon at the top right corner would be even better :-)

**Comment by tegioz** [comment]
The problem is that the landscape data file is getting more complex by the day, so we need to be careful about extending it.

Not long ago we added the `package_url` field for #385 (you requested it actually), recently another user asked for the one I just linked above and now we have this one 😅 So we thought this would keep happening every now and then, and provided a generic mechanism to manage 'other' links.

We'll add this one, as probably a generic documentation link deserves its own icon at the top, but it's important that we rely as much as possible on `other_links` going forward 😇

**Comment by jmertic** [comment]
I totally understand and appreciate it, @tegioz. 

I'll save my request for "most relevant xkcd" comic for the `other_links` section ;-)

**Comment by tegioz** [comment]
Closed by #669
